### ISSUE TITLE
Compatibility with newer versions 

### ISSUE THREAD

**Issue by NCDyson** [unknownbrackets/ppsspp-virtfs-tools#1]
Is this compatible with newer versions of ppsspp? If not, could you recommend a revision that it's compatible with?

**Comment by unknownbrackets** [comment]
This should be compatible with the latest version of PPSSPP still - we haven't introduced any breaking changes that would change the API used.

Are you running into any problems using this in the latest version?

-[Unknown]

**Comment by NCDyson** [comment]
The issue turned out to be me not understanding how to use it properly. 

However, I've noticed that it doesn't appear to work with files opened with sceIoOpenAsync.

**Comment by unknownbrackets** [comment]
Hmm.  Can you give more details or reproduction steps?

Both sceIoOpen and sceIoOpenAsync go through the same code in PPSSPP, and aren't even distinguishable by `VirtualDiscFileSystem` which is what handles the actual file IO and plugins.

-[Unknown]

**Comment by NCDyson** [comment]
I've got the dll in the base directory of the emulator, the .ppsspp-index.lst in the base directory of the extracted game ISO. 

I've edited the .ppsspp-index.lst file entry of the file i'm trying to use the passthru dll with set to

> "0x00004f06 PSP_GAME/USRDIR/loaddata.cpk:passthru"

I see what I think may now just be the emulator checking the files with the passthru dll in the debug log:

> 20:22:017 EmuThread.cpp:173 I[BOOT]: Done.
> 20:22:201 FileSystems\VirtualDiscFileSystem.cpp:789 D[FileSys]: passthru handler initialized
> 20:22:201 FileSystems\VirtualDiscFileSystem.cpp:789 D[FileSys]: Opened file C:/prjPsp/liso\/PSP_GAME/USRDIR/loaddata.cpk
> 20:22:201 FileSystems\VirtualDiscFileSystem.cpp:789 D[FileSys]: Seek to offset 0x00000000(2)
> 20:22:201 FileSystems\VirtualDiscFileSystem.cpp:789 D[FileSys]: Closed file
> 20:22:202 FileSystems\DirectoryFileSystem.cpp:190 D[FileSys]: Actually opening C:/prjPsp/liso\PSP_GAME\PARAM.SFO
> 20:22:203 FileSystems\DirectoryFileSystem.cpp:190 D[FileSys]: Actually opening C:/prjPsp/liso\PSP_GAME\ICON0.PNG
> 20:22:201 FileSystems\VirtualDiscFileSystem.cpp:789 D[FileSys]: passthru handler initialized
> 20:22:201 FileSystems\VirtualDiscFileSystem.cpp:789 D[FileSys]: Opened file C:/prjPsp/liso\/PSP_GAME/USRDIR/loaddata.cpk
> 20:22:201 FileSystems\VirtualDiscFileSystem.cpp:789 D[FileSys]: Seek to offset 0x00000000(2)
> 20:22:201 FileSystems\VirtualDiscFileSystem.cpp:789 D[FileSys]: Closed file

but down later in the debug log when I see the sceIO debug strings, I see nothing to indicate that the passthru dll is being used. I've attached a debug log from the emulator on the off chance it's remotely helpful.

Not sure if it's actually broken, or if I've missed a step, or just flat out misunderstood the purpose/use of the virtfs system.
[ppsspplog.txt](https://github.com/unknownbrackets/ppsspp-virtfs-tools/files/288491/ppsspplog.txt)

**Comment by unknownbrackets** [comment]
```
20:22:201 FileSystems\VirtualDiscFileSystem.cpp:789 D[FileSys]: Opened file C:/prjPsp/liso\/PSP_GAME/USRDIR/loaddata.cpk
...
20:23:748 CriThread    D[FileSys]: FileSystems\DirectoryFileSystem.cpp:190 Actually opening C:/prjPsp/liso\PSP_GAME\USRDIR\loaddata.cpk
```

Hmm, I wonder if there's some issue here with path normalization.  Hmm, oops.  Try changing `PSP_GAME/USRDIR/loaddata.cpk` to `/PSP_GAME/USRDIR/loaddata.cpk` in your index... I think that may be it.

-[Unknown]

**Comment by NCDyson** [comment]
thank you for taking the time to look into the issue. As of now, the issue appears to be resolved.

**Comment by unknownbrackets** [comment]
Great, thanks for finding that other bug with get info... surprised it wasn't caught before.  Closing.

-[Unknown]
